artphoto/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^photo/', include('photo.urls')),
    url(r'^', include('photo.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url
from . import views


app_name = 'photo'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'), 
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<album_id>[0-9]+)/detail_change/$', views.detail_change, name='detail_change'),
    url(r'album/add/$', views.albumCreate, name='album-add'),
    url(r'album/(?P<album_id>[0-9]+)/$', views.convertImage, name='convert'),
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
    url(r'album/(?P<album_id>[0-9]+)/download/$', views.get_image, name='get_image'),

]

photo/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Permission, User


class AlbumPhoto(models.Model):
    user = models.ForeignKey(User, default=1)
    photo_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=100)
    photo_logo = models.ImageField(
        null=True, 
        blank=True,
        height_field = "height_field",
        width_field = "width_field",
        )
    
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    
    
    def get_absolute_url(self):
        return reverse('photo:detail', kwargs={"id": self.id})

    def __str__(self):
        return self.photo_title + ' - ' + self.genre
    

photo/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import AlbumPhoto


class AlbumForm(forms.ModelForm):

    class Meta:
        model = AlbumPhoto
        fields = ['photo_title', 'genre', 'photo_logo']

class AlbumForm1(forms.ModelForm): # не правильно - но работает! hidden how?

    class Meta:
        model = AlbumPhoto
        fields = ['photo_title', 'genre', 'photo_logo','height_field','width_field']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class ImageChangeForm(forms.Form):
    CHOICES = (
        ('L', 'black-white'),
        ('BLUR', 'blur'),
        ('1', 'white-pixel'),


        )
    Choise = forms.ChoiceField(choices=CHOICES, required=True)
    

photo/views.py
import random
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.db.models import Q

from wsgiref.util import FileWrapper
import mimetypes

from photo.forms import AlbumForm, UserForm, AlbumForm1
from .models import AlbumPhoto
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext

from PIL import Image, ImageFilter, ImageDraw 
import os
from artphoto.settings import BASE_DIR

IMAGE_FILE_TYPES = ['jpg', 'png']

def convertImage(request, album_id):
	if request.method == "POST":
		photo = AlbumPhoto.objects.get(pk = album_id)
		img = Image.open(photo.photo_logo.path)
		draw = ImageDraw.Draw(img) 
		width = img.size[0]
		height = img.size[1] 	
		pix = img.load() 

		if request.POST['preset'] == 'L':
			img = img.convert("L") 

		if request.POST['preset'] == 'BLUR':
			img == img.filter(ImageFilter.BLUR)

		if request.POST['preset'] == 'FIND_EDGES':
			img = img.filter(ImageFilter.FIND_EDGES)

		if request.POST['preset'] == "1":
			img = img.convert("1")

		if request.POST['preset'] == "90":
			img = img.rotate(90)

		if request.POST['preset'] == "180":
			img = img.rotate(180)

		if request.POST['preset'] == "270":
			img = img.rotate(270)

		if request.POST['preset'] == "360":
			img = img.rotate(360)

		if request.POST['preset'] == "ghost":
			for i in range(width):
				for j in range(height):
					a = pix[i, j][0]
					b = pix[i, j][1]
					c = pix[i, j][2]
					draw.point((i, j), (255 - a, 255 - b, 255 - c))
		
		if request.POST['preset'] == "pixel":
			factor = 70
			for i in range(width):
				for j in range(height):
					rand = random.randint(-factor, factor)
					a = pix[i, j][0] + rand
					b = pix[i, j][1] + rand
					c = pix[i, j][2] + rand
					if (a < 0):
						a = 0
					if (b < 0):
						b = 0
					if (c < 0):
						c = 0
					if (a > 255):
						a = 255
					if (b > 255):
						b = 255
					if (c > 255):
						c = 255
					draw.point((i, j), (a, b, c)) 

		if request.POST['preset'] == "light":
			factor = 100
			for i in range(width):
				for j in range(height):
					a = pix[i, j][0] + factor
					b = pix[i, j][1] + factor
					c = pix[i, j][2] + factor
					if (a < 0):
						a = 0
					if (b < 0):
						b = 0
					if (c < 0):
						c = 0
					if (a > 255):
						a = 255
					if (b > 255):
						b = 255
					if (c > 255):
						c = 255
					draw.point((i, j), (a, b, c))

		if request.POST['preset'] == "night":
			factor = -100
			for i in range(width):
				for j in range(height):
					a = pix[i, j][0] + factor
					b = pix[i, j][1] + factor
					c = pix[i, j][2] + factor
					if (a < 0):
						a = 0
					if (b < 0):
						b = 0
					if (c < 0):
						c = 0
					if (a > 255):
						a = 255
					if (b > 255):
						b = 255
					if (c > 255):
						c = 255
					draw.point((i, j), (a, b, c))

		if request.POST['preset'] == "300":
			basewidth = 300
			wpercent = (basewidth / float(img.size[0]))
			hsize = int((float(img.size[1]) * float(wpercent)))
			img = img.resize((basewidth, hsize))
			
		if request.POST['preset'] == "128":
			basewidth = 128
			wpercent = (basewidth / float(img.size[0]))
			hsize = int((float(img.size[1]) * float(wpercent)))
			img = img.resize((basewidth, hsize))

		if request.POST['preset'] == "512":
			basewidth = 512
			wpercent = (basewidth / float(img.size[0]))
			hsize = int((float(img.size[1]) * float(wpercent)))
			img = img.resize((basewidth, hsize))

		if request.POST['preset'] == "return":
			photo = AlbumPhoto.objects.get(pk = album_id)
			photo_name = photo.photo_logo.name
			photo_way = os.path.join(BASE_DIR, 'media')
			name_resolution_img = photo_name.split('.')[1]
			if name_resolution_img == 'jpg':
				omg_img = photo_way +'/' + photo_name.split('.')[0] + '_' + str(album_id)+'.jpg'
			else:
				omg_img = photo_way +'/' + photo_name.split('.')[0] + '_' + str(album_id)+'.png'      
			img = Image.open(omg_img)
			img.save(photo_way + '/' + photo_name)
			img.close()
			return HttpResponseRedirect('http://localhost:8000/'+'photo/'+str(album_id)+'/detail_change/')

		if request.POST['preset'] == "return_main":
			photo = AlbumPhoto.objects.get(pk = album_id)
			photo_name = photo.photo_logo.name
			photo_way = os.path.join(BASE_DIR, 'media')
			name_resolution_img = photo_name.split('.')[1]
			if name_resolution_img == 'jpg':
				omg_img = photo_way +'/' + photo_name.split('.')[0] + '_' + str(album_id)+'.jpg'
			else:
				omg_img = photo_way +'/' + photo_name.split('.')[0] + '_' + str(album_id)+'.png'      
			img = Image.open(omg_img)
			img.save(photo_way + '/' + photo_name)
			img.close()
			return HttpResponseRedirect('http://localhost:8000/')
		img.save(photo.photo_logo.path)
		img.close()
		del draw
	return HttpResponseRedirect('http://localhost:8000/'+'photo/'+str(album_id)+'/detail_change/')



def get_image(request, album_id):
    photo = AlbumPhoto.objects.get(pk=album_id)
    photo_name = photo.photo_logo.name
    file_path = os.path.join(BASE_DIR, 'media') +"/"+ photo_name

    wrapper = FileWrapper(open(file_path, 'rb'))
    
    response = HttpResponse(wrapper, content_type="image/jpg")
    response['Content-Length'] = os.path.getsize(file_path)
    filename = "Image_%s.jpg" %(str(album_id))
    content = "attachment; filename='%s'" %(filename)
    response['Content-Disposition'] = content
    return response

class AlbumDelete(DeleteView):
	model = AlbumPhoto
	success_url = reverse_lazy('photo:index')  


def index(request):
	if not request.user.is_authenticated():
		return render(request, 'photo/index_no_user.html')
	else:
		photo_list = AlbumPhoto.objects.filter(user=request.user)
		query = request.GET.get("q")
		if query:
			photo_list = photo_list.filter(
				Q(photo_title__icontains=query)
			).distinct()
			return render(request, 'photo/index.html',{
				'photo_list': photo_list,
		
			})
		else:
			return render(request, 'photo/index.html', {"photo_list": photo_list})


def detail_change(request, album_id):
	albumphoto = get_object_or_404(AlbumPhoto, pk=album_id)
	return render(request,'photo/detail_change.html',{"albumphoto": albumphoto},)

def detail(request, album_id):
	if not request.user.is_authenticated():
		return render(request, 'photo/detail.html',{"albumphoto": albumphoto})
	else:
		form = AlbumForm1()
		photo = AlbumPhoto.objects.get(pk = album_id)
		name_o = photo.photo_logo.path.split('//')[-1]
		name_i = name_o.split('.')[0]
		name_r = name_o.split('.')[-1]
		photo_way = os.path.join(BASE_DIR, 'media')
		img = Image.open(photo.photo_logo.path)
		if name_r == 'jpg':
			img.save(name_i + '_' + str(album_id) + '.jpg')
		else:
			img.save(name_i + '_' + str(album_id) + '.png')
			
		img.close()
		user = request.user
		albumphoto = get_object_or_404(AlbumPhoto, pk=album_id)
		return render(request,'photo/detail.html',{"albumphoto": albumphoto, 'user': user, 'form': form})

def albumCreate(request):
	if not request.user.is_authenticated(): 
		return render(request, 'photo/check_login.html')
	else:
		form = AlbumForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			albumphoto = form.save(commit=False)
			albumphoto.user = request.user
			albumphoto.photo_logo = request.FILES['photo_logo']
			file_type = albumphoto.photo_logo.url.split('.')[-1]
			file_type = file_type.lower()
			if file_type not in IMAGE_FILE_TYPES:       
				context = {
					'photo': albumphoto,
					'form': form,
					'error_message': 'Image file must be JPG or PNG',
				}
				return render(request, 'photo/albumphoto_form.html', context)            
			albumphoto.save()
			return render(request, 'photo/detail_create.html', {'albumphoto': albumphoto})
		context = {
			"form": form,
		}
		return render(request, 'photo/albumphoto_form.html', context)

class UserFormView(View):
	form_class = UserForm
	template_name = 'photo/register.html'

	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

	def post(self, request):
		form = self.form_class(request.POST)
		if form.is_valid():
			user = form.save(commit=False)
			username = form.cleaned_data['username']
			password= form.cleaned_data['password']
			user.set_password(password)
			user.save()
			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect('photo:index')
		return render(request, self.template_name, {'form': form})

def logout_user(request):
	logout(request)
	form = UserForm(request.POST or None)
	context = {
		"form": form,
	}
	return render(request, 'photo/login.html', context)

def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				photo_list = AlbumPhoto.objects.filter(user=request.user)
				return render(request, 'photo/index.html', {'photo_list': photo_list})
			else:
				return render(request, 'photo/login.html', {'error_message': 'Your account has been disabled'})
		else:
			return render(request, 'photo/login.html', {'error_message': 'Invalid login'})
	return render(request, 'photo/login.html')

photo/templates/photo/albumphoto_form.html
{% extends 'photo/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %} active {% endblock %}

{% block body %}

<div id="center" class="container">
    <div class="row">
        <div class="col-sm-12 col-md-15">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Photo</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'photo/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>

</div>
{% endblock %}

photo/templates/photo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Photo{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'photo/style.css' %}">
    <link rel="icon" type="image/png" href="{%  static 'photo/favicon.ico' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cerulean/bootstrap.min.css" rel="stylesheet">
    
    
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'photo:index' %}"><span class="glyphicon glyphicon-camera" aria-hidden="true"></span>&nbsp;Photo</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="">
                <a href="{% url 'photo:register' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Registeration User</a></li>
            <li class="">
                <a href="{% url 'photo:login_user' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Login</a></li>
        </ul>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'photo:album-add' %}">
                        <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>&nbsp; Add Photo
                    </a>
                </li>
                <li class="">
                <li class="">
                    <a href="{% url 'photo:logout_user' %}">
                        <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
      </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

photo/templates/photo/check_login.html
{% extends 'photo/base.html' %}

{% block body %}
<style>
 div 
   #center { text-align: center; }
</style>
<div class="albums-container container-fluid">
    <div class="row">
            <div class="starter-template" id="center">
                <h4>Please, <a href="{% url 'photo:register' %}">Click here</a> to register a 
                                    New Account or <a href="{% url 'photo:login_user' %}">Loggin</a></h4>
        </div>
    </div>
</div>

{% endblock %}

photo/templates/photo/detail.html
{% extends 'photo/base.html' %}
{% block title %}Album Photo{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}


    <div class="col-sm-6 col-sm-offset-3">
      <div style="text-align: center" class="thumbnail">  
              {% if albumphoto.photo_logo %}
                  <img src="{{ albumphoto.photo_logo.url }}" class='img-responsive'>
              {% else %}
                  <h3>No image to display</h3>
              {% endif %}
          </a>
        <div class="caption">
          <!--<label> Resolution image: {{ hidden }}</label>  HHHHHHHHHHHMMMMMMMMMMMMMMM........... I don't know HOW?-->
          <label> Resolution image(origin): {{ albumphoto.height_field }} x {{ albumphoto.width_field }} </label>

          <p>
            <a href="{% url 'photo:album-add' %}" class="btn btn-primary" role="button">Add New Photo</a>
            <a href="{% url 'photo:detail_change' albumphoto.id %}" class="btn btn-primary" role="button">Change Details</a>
            <a href="{% url 'photo:index' %}" class="btn btn-primary" role="button">Back Main Page</a>
          </p>
        </div>
      </div>
 
{% endblock %}
 

              
                        

photo/templates/photo/detail_change.html
{% extends 'photo/base.html' %}
{% block title %}Album Photo{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}


    <div class="col-sm-6 col-sm-offset-3">
      <div class="thumbnail">  
              {% if albumphoto.photo_logo %}
                  <img src="{{ albumphoto.photo_logo.url }}" class='img-responsive'>
              {% else %}
                  <h3>No image to display</h3>
              {% endif %}
          </a>
        <div class="caption">
            <div style="text-align: center"class="page-header">
                <h1>{{ albumphoto.photo_title }}</h1>
            </div>
          <p>

              <h1>Choices:</h1>
            <form class="form-horizontal" role="form" action="{% url 'photo:convert' albumphoto.id %}" method="POST">
                {% csrf_token %}
                <p class="bg-success">
                <br>
                <label class="control-label col-sm-2">
                    Simple:
                </label>
                <button name="preset" value="L" class="btn btn-primary btn-sm">Image Black-Write</button>
                <button name="preset" value="BLUR" class="btn btn-primary btn-sm">Image Blur</button>
                <button name="preset" value="FIND_EDGES" class="btn btn-primary btn-sm">Image Edges</button>
                <button name="preset" value="1" class="btn btn-primary btn-sm">Image White Pixel's</button>
                <br>
                <br>
                </p>
                
                <p class="bg-info">
                <br>
                <label class="control-label col-sm-2">
                    Image Rotate:
                </label>
                <button name="preset" value="90" class="btn btn-primary btn-sm">Rotate Image on 90</button>
                <button name="preset" value="180" class="btn btn-primary btn-sm">Rotate Image on 180</button>
                <button name="preset" value="270" class="btn btn-primary btn-sm">Rotate Image on 270</button>
                <button name="preset" value="360" class="btn btn-primary btn-sm">Rotate Image on 360</button>
                <br>
                <br>
                </p>

                <p class="bg-warning">
                <br>
                <label class="control-label col-sm-2">
                    Hard Change:
                </label>
                <button name="preset" value="ghost" class="btn btn-primary btn-sm">Image Ghost</button>
                <button name="preset" value="pixel" class="btn btn-primary btn-sm">Image Color Pixel</button>
                <button name="preset" value="light" class="btn btn-primary btn-sm">Image Light</button>
                <button name="preset" value="night" class="btn btn-primary btn-sm">Image Night</button>
                <br>
                <br> 
                </p>

                <p class="bg-danger">
                <br>
                <label class="control-label col-sm-2">
                    Resolution:
                </label>
                <button name="preset" value="300" class="btn btn-primary btn-sm">300 pixels</button>
                <button name="preset" value="128" class="btn btn-primary btn-sm">128 pixels</button>
                <button name="preset" value="512" class="btn btn-primary btn-sm">512 pixels</button>
                <button name="preset" value="return" class="btn btn-success btn-sm">Return image</button>
                <br>
                <br>
                </p>


                <!--<select multiple class="form-control">
                    <option>1</option>
                    <option>2</option>     HHHHHHHHHHHHHHHHHHHHHHHMMMMMMMMMMMMMMMMMMMMMM...........
                    <option>3</option>          HHHHHHHHHHHHHHHHHHHHHHHMMMMMMMMMMMMMMMMMMMMMM...........
                    <option>4</option>                  HHHHHHHHHHHHHHHHHHHHHHHMMMMMMMMMMMMMMMMMMMMMM........... I don't know HOW?
                    <option>5</option>
                </select>-->
            </form>
          </p>
          </br>
          
        </div>
      </div>
 
{% endblock %}

photo/templates/photo/detail_create.html
{% extends 'photo/base.html' %}
{% block title %}Album Photo{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}


    <div class="col-sm-6 col-sm-offset-3">
      <div style="text-align: center" class="thumbnail">
              {% if albumphoto.photo_logo %}
                  <img src="{{ albumphoto.photo_logo.url }}" class='img-responsive' >
              {% else %}
                  <h3>No image to display</h3>
              {% endif %}
          </a>
        <div class="caption">
          <h3>{{ albumphoto.photo_title }}</h3>
          <p>
            <a href="{% url 'photo:album-add' %}" class="btn btn-primary" role="button">Add New Photo</a>
            <a href="{% url 'photo:detail' albumphoto.id %}" class="btn btn-primary" role="button">View Details</a>
            <a href="{% url 'photo:index' %}" class="btn btn-primary" role="button">Back Main Page</a>
          </p>
        </div>
      </div>
 <a href="{% url 'photo:album-add' %}">
{% endblock %}

photo/templates/photo/form_template.html
{% for field in form %}
    <div class="form-group" xmlns="http://www.w3.org/1999/html">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>    
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

photo/templates/photo/index.html
{% extends 'photo/base.html' %}
{% block photo_list_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">
            <div class="starter-template" style="text-align: center;">
                <h1>Hello {{ user.username }} !!!</h1>
                <h4>You can change image grafity, just push to "View Details" Button.</h4>
                <h4>If didn't like this change, You can back Image on "Return Image"</h4>
            </div>

        {% if photo_list %}
            {% for albumphoto in photo_list %}
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-md-6 col-md-push-3">
                        <div class="thumbnail">
                            <a href="{% url 'photo:detail' albumphoto.id %}">
                                <img src="{{ albumphoto.photo_logo.url }}" class="img-responsive">
                            </a>
                            <div class="caption">
                                <div class="btn-group">
                                    <h2>{{ albumphoto.photo_title }}</h2>
                                    <form action="{% url 'photo:convert' albumphoto.id %}" method="POST">
                                        {% csrf_token %}

                                        <a class="btn btn-primary" href="{% url 'photo:detail' albumphoto.id %}">View Details</a>
                                        <button name="preset" value="return_main" class="btn btn-danger">Return Image</button>

                                    </form>
                                    <br>
                                    <a class="btn btn-success" href="{% url 'photo:get_image' albumphoto.id %}">Download</a>
                                    <form action="{% url 'photo:album-delete' albumphoto.id %}" method="post" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="album_id" value="{{ album.id }}" />
                                            <button type="submit" class="btn btn-default">
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            



            {% endfor %}
        {% else %}
            <div id="center" class="col-sm-12">
                <br>
                <a href="{% url 'photo:album-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Photo
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

photo/templates/photo/index_no_user.html
{% extends 'photo/base.html' %}

{% block body %}
<style>
 div 
   #center { text-align: center; }
</style>
<div class="albums-container container-fluid">
    <div class="row">
            <div class="starter-template" id="center">
                <h4>Please, <a href="{% url 'photo:register' %}">Click here</a> to register a 
                                    New Account or <a href="{% url 'photo:login_user' %}">Loggin</a></h4>
        </div>
    </div>
</div>

{% endblock %}

photo/templates/photo/login.html
{% extends 'photo/base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}

<div id="center" class="container">
    <div class="row">
        <div class="col-sm-12 col-md-15">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'photo:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div  class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                               Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'photo:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

photo/templates/photo/register.html
{% extends 'photo/base.html' %}
{% block title %}Register User{% endblock %}


{% block body %}

<div id="center" class="container">
    <div class="row">
        <div class="col-sm-12 col-md-15">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a New Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'photo/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>

</div>
{% endblock %}